### PR TITLE
Fix misplaced Outer/Inner names when using named() on Each

### LINKED ISSUE #1639: Each inverts names
In 3.0, the `Each` validator is inverting names.

Consider this example:

```php
test('Inner and outer names.', catchAll(
    fn() => v::named('my_file.txt', v::each(v::named('line', v::intType())))->assert(['a', 'b', 'c']),
    fn(string $message, string $fullMessage, array $messages) => expect()
        ->and($fullMessage)->toBe(<<<'FULL_MESSAGE'
        - Each item in my_file.txt must be valid
          - `.0` must be an integer
          - `.1` must be an integer
          - `.2` must be an integer
        FULL_MESSAGE)
));
```

In this scenario, `['a', 'b', 'c']` is the return of some `file('my_file.txt')`, a text file with 3 lines containing each of those letters.

Currently, it does not pass, and generates `Each item in line must be valid`.

This example is clearer than the ones in the codebase that use `Wrapper` and `Wrapped` and are easy to overlook. I'm using `my_file.txt` and `line` as a real example (each line of my_file.txt must be XXX, a common type of validation).

Ideally, if the validator passed to `Each` has a name, we want this:

```php
test('Inner and outer names.', catchAll(
    fn() => v::named('my_file.txt', v::each(v::named('line', v::intType())))->assert(['a', 'b', 'c']),
    fn(string $message, string $fullMessage, array $messages) => expect()
        ->and($fullMessage)->toBe(<<<'FULL_MESSAGE'
        - Each item in my_file.txt must be valid
          - `.0` (<- line) must be an integer
          - `.1` (<- line) must be an integer
          - `.2` (<- line) must be an integer
        FULL_MESSAGE)
));
```

We could omit `(<- line)` in the messages if the validator passed does not have an explicit name.

That would allow us to have a descriptive message of the whole (in this case, the file) and also the part (each line) with clear keys visible as well.

### PR DESCRIPTION
**Pull request by alganet**
The Each validator was using "Outer" names (the name applied to the parent) in child results and vice-versa.

This commit fixes it, and also streamlines the Result class, introducing helper `mapChildren` and `mapAdjacent` methods and removing unecessary recursive array_maps.

Named children now also display their names, allowing users to create more meaningful messages that do not spam nested `.0`...`.0`...etc numeric keys which could be confusing. If the user does not name them, the previous behavior is kept.

---

This fixes #1639

### CODE REVIEW

File: src/Result.php [hunk 1]
```diff
@@ -180,25 +176,7 @@ public function withNameFrom(Validator $validator): self
...
-            'hasPrecedentName' => true,
-            'adjacent' => $this->adjacent?->withNameFrom($validator),
-            'children' => array_map(
-                static fn(Result $child) => $child->withNameFrom($validator),
-                $this->children,
-            ),
-        ]);
-    }
-
-    public function withInput(mixed $input): self
```
Comment (henriquemoody) [inline src/Result.php:192]: The `withInput()` was buggy, I was going to send a fix somewhere this week. This change just keeps the buggy behavior, though.

The `withInput()` should also overwrite the input of adjacent result (see [this](https://github.com/henriquemoody/Validation/commit/507b46603c846143adb274d591c5a441077166d4#diff-ef70a67aac7e66a56477071c98893e9698e5c2b8fabd1f92adb7890dd8cfe764R196)). I think it should overwrite the input of the children, but the conditions should not only take the input into account, but also if the path is the same or not.

It's okay to keep the code as is, but we should provide a `withInput()` in v3

File: src/Message/Formatter/NestedArrayFormatter.php [hunk 2]
```diff
@@ -45,6 +45,8 @@ public function format(Result $result, Renderer $renderer, array $templates): ar
                 $renderer,
                 $templates,
                 $hasString,
+                $result,
+                hasRoot: count($children) > 1,
```
Comment (henriquemoody) [inline src/Message/Formatter/NestedArrayFormatter.php]: For a better understanding, it would be great if this boolean is saved in a variable that can also be used in line 54

File: src/Message/Formatter/NestedArrayFormatter.php [hunk 3]
```diff
@@ -91,12 +93,14 @@ private function appendMessage(
         Renderer $renderer,
         array $templates,
         bool $hasString,
+        Result $parent,
+        bool $hasRoot,
```
Comment (henriquemoody) [inline src/Message/Formatter/NestedArrayFormatter.php]:
```suggestion
        bool $isParentVisible,
```
Nitpick, hasRoot is understandable in context

File: src/Result.php [hunk 4]
```diff
@@ -247,4 +221,15 @@ public function allowsAdjacent(): bool
 
         return count($childrenThatAllowAdjacent) === 1;
     }
+
+    /** @return array<Result> */
+    private function mapChildren(callable $callback): array
```
Comment (henriquemoody) [inline src/Result.php:226]: This is great! I was going to do that next time I had to do anything with the children again

File: src/Result.php [hunk 5]
```diff
@@ -247,4 +221,15 @@ public function allowsAdjacent(): bool
...
+    {
+        return $this->children === [] ? [] : array_map($callback, $this->children);
+    }
+
+    private function mapAdjacent(callable $callback): Result|null
```
Comment (henriquemoody) [inline src/Result.php]: I see less of a reason for this one, though. The nullsafe gives that for us for free, why creating this method?

**Review by henriquemoody — COMMENTED** [review]
Awesome work, and great catch! I think we should get to an agreement regarding the `withInput()` before merging this one, though.

File: src/Result.php (hunk 1 above)
Comment (alganet) [reply src/Result.php:192]: @henriquemoody I didn't knew!

Can you open an issue for that one so we can track it?

File: src/Message/Formatter/NestedArrayFormatter.php (hunk 2 above)
Comment (alganet) [reply src/Message/Formatter/NestedArrayFormatter.php]: Line 54 is `count($messages)`, not `count($children)`. Those differ!

File: src/Result.php (hunk 5 above)
Comment (alganet) [reply src/Result.php]: It was doing more during a local refactor, but then it didn't, and I forgot to put this back how it was. Thanks!

File: src/Message/Formatter/NestedArrayFormatter.php [hunk 6]
```diff
@@ -45,6 +45,8 @@ public function format(Result $result, Renderer $renderer, array $templates): ar
                 $renderer,
                 $templates,
                 $hasString,
+                $result,
+                hasParentVisible: count($children) > 1,
```
Comment (henriquemoody) [inline src/Message/Formatter/NestedArrayFormatter.php]: I think it should be either `isParentVisible` or `hasVisibleParent`

File: src/Result.php (hunk 1 above)
Comment (henriquemoody) [reply src/Result.php:192]: I opened #1641 instead

File: src/Message/Formatter/NestedArrayFormatter.php (hunk 2 above)
Comment (henriquemoody) [reply src/Message/Formatter/NestedArrayFormatter.php]: You're absolutely right, there's an `array_reduce()`!

**Review by henriquemoody — APPROVED** [review]
