### PR TITLE
Issue #260: Now using  Respect\Validation exceptions only

### LINKED ISSUE #260: Use only Respect\Validation exceptions instead of native ones
There is some places we are using native SPL exceptions and it's great but users cannot know when the exception is ours or not.
We can keep using SPL exceptions but also having our own exceptions.

**Base Exception interface**
```php
namespace Respect\Validation\Exceptions;

interface ExceptionInterface
{
}
```

**ValidationException**
```php
namespace Respect\Validation\Exceptions;

use InvalidArgumentException;

class ValidationException extends InvalidArgumentException implements ExceptionInterface
{
}
```

**ComponentException**
```php
namespace Respect\Validation\Exceptions;

use Exception;

class ComponentException extends Exception implements ExceptionInterface
{
}
```

etc..

### PR DESCRIPTION
**Pull request by AndyWendt**
### Added new types:

* `ExceptionInterface`: all Respect\Validation\Exceptions implement through inheritance
* `ValidatorExceptionInterface`: implemented only by AllOfException.  This allows the end users to know when there has been a Validator exception rather than just any of our exceptions.

### Changed Tests and Readme

* `ValidatorTest` and `README.md` now use `ValidatorExceptionInterface`

* Added *Exception Types* section to `README.md`

Fix #260.

### CODE REVIEW

File: library/Exceptions/ExceptionInterface.php [hunk 1]
```diff
@@ -0,0 +1,6 @@
+<?php  namespace
```
Comment (henriquemoody) [inline library/Exceptions/ExceptionInterface.php]: Please keep the same standard of the other files

File: library/Exceptions/ValidatorExceptionInterface.php [hunk 2]
```diff
@@ -0,0 +1,9 @@
+<?php
+namespace Respect\Validation\Exceptions;
+
+interface ValidatorExceptionInterface
+{
+    public function getMainMessage();
+    public function findMessages(array $paths);
+    public function getFullMessage();
+}
```
Comment (henriquemoody) [inline library/Exceptions/ValidatorExceptionInterface.php]: New line at end of the file is required

File: library/Exceptions/ExceptionInterface.php [hunk 3]
```diff
@@ -0,0 +1,6 @@
...
+Respect\Validation\Exceptions;
+
+interface ExceptionInterface
+{
+}
```
Comment (henriquemoody) [inline library/Exceptions/ExceptionInterface.php]: New line here is required

File: library/Exceptions/AllOfException.php [hunk 4]
```diff
@@ -1,7 +1,7 @@
 <?php
 namespace Respect\Validation\Exceptions;
 
-class AllOfException extends AbstractGroupedException
+class AllOfException extends AbstractGroupedException implements ValidatorExceptionInterface
```
Comment (henriquemoody) [inline library/Exceptions/AllOfException.php]: `AbstractGroupedException` extends `AbstractNestedException` which extends `ValidationException`.

**Comment by henriquemoody** [comment]
`ValidatorExceptionInterface` is unnecessary since if only works for concrete class `ValidatorException`. 
Please, remove `ValidatorExceptionInterface` and use `ValidatorException` type instead.

**Comment by AndyWendt** [comment]
I will fix the issues.  

There is no `ValidatorException`.  You have two Exception types through inheritance:

1. `ValidationException`
    * Which has the method `getMainMessage()`
2. `AbstractNestedException`
    * Which has the methods `findMessages()` and `getFullMessage()`.  It also is a `ValidationException` through inheritance.
    * Only some of the classes extend `AbstractNestedException` so **not all of them have all of the exception methods that you promise end users.**  

As far as I can tell, `assert()`  always throws an `AllOfException` which extends `AbstractNestedException`.  Right now you are recommending type-hinting either `\InvalidArgumentException` or `\Exception` *but in the examples you call methods in the `catch` block that are not in either of those exceptions*.  **This is a problem since there is no contract (i.e. `interface`) that says what methods are going to be available on the thrown exception.**  

**You could use a concrete class** but that would probably violate the [Dependency Inversion Principle](en.wikipedia.org/wiki/Dependency_inversion_principle) and you would have to extend `AbstractNestedException`.  Also, **what if you want to swap out the type of exception** that is thrown in the future?  

If you have the end users depend upon an `interface` it is not a problem--you just have to have the thrown exception conform the contract provided by the `interface`.

**It is your package and your code** so I will do what you like.  I am just trying to help out.  Have a great day! :)

File: library/Exceptions/AllOfException.php (hunk 4 above)
Comment (AndyWendt) [inline library/Exceptions/AllOfException.php]: See my comment below.

**Comment by henriquemoody** [comment]
I wrote the wrong name, when I wrote `ValidatorException` it was `ValidationException` instead.

Yes, the examples are wrong, they also violates [Liskov substitution principle](http://en.wikipedia.org/wiki/Liskov_substitution_principle), so they really need to be replaced.

You're right about almost everything, I will make some notes.

PS.: This is not my package and there are code of [lots of people](https://github.com/Respect/Validation/graphs/contributors). I'm a collaborator with owner privileges.
PSS.: Every contribution is very important for us, be sure that any issue/pull request will be closed without a good reason.

File: README.md [hunk 5]
```diff
@@ -183,9 +195,11 @@ validation report. There is also a `check()` method that returns an Exception
 only with the first error found:
 
 ```php
+import Respect\Validation\Exceptions\ValidatorExceptionInterface
+
 try {
     $usernameValidator->check('really messed up screen#name');
-} catch(\InvalidArgumentException $e) {
+} catch(ValidatorExceptionInterface $e) {
     echo $e->getMainMessage();
```
Comment (henriquemoody) [inline README.md]: `check()` may throws `ValidatorException`, like `NotEmptyException`, `NoWhitespaceException` which is not type of `ValidatorExceptionInterface`.

File: README.md [hunk 6]
```diff
@@ -108,15 +108,25 @@ $usernameValidator->validate('alexandre gaigalas'); //false
 $usernameValidator->validate('#$%');                //false
 ```
 
+### Exception Types
+
+* `Respect\Validation\Exceptions\ValidatorExceptionInterface`:
+    * Used when `assert()` is called.
+    * Interface has three methods: `getFullMessage()`, `findMessages()`, and `getMainMessage()`.
```
Comment (henriquemoody) [inline README.md]: `getMainMessage()` is present on `ValidationException`.

**Comment by henriquemoody** [comment]
We may have two types here:

- Type 1: `::getMainMessage()`
- Type 2: `::getMainMessage()`, `::getFullMessage()` and `::findMessages()` (it may extends Type 1)

The reason why I was told you about using the concrete class is because `ValidationException` has too many public methods as [you can see](https://github.com/Respect/Validation/blob/master/library/Exceptions/ValidationException.php) but I agree on creating these two types.

I will wait on your changes. Do what you think is better.

**Comment by AndyWendt** [comment]
I will create the two types and apply them to `ValidationException` and `AbstractNestedException`.  Do you have any suggestions for naming?  

Ok. I really wasn't trying to be snarky when I said that it was your code.

**Comment by henriquemoody** [comment]
No problem!! :smile: 

I'm not good with names, maybe some of @Respect/troubleshooters have better ones, but mines are:

- `ValidationExceptionInterface`
- `NestedValidationExceptionInterface`

How about yours, @AndyWendt?

File: README.md (hunk 5 above)
Comment (AndyWendt) [inline README.md]: You are right.  I tried: 

```php
try {
    $usernameValidator = v::alnum()->noWhitespace()->length(1,15);
    $usernameValidator->check('really messed up screen#name');
} catch (\Exception $e) {
    var_dump(get_class($e));
    var_dump($e->getMainMessage());
    var_dump($e->getFullMessage());
}
```
When `$e->getFullMessage()` is called **it causes an undefined method fatal error**.

**Comment by AndyWendt** [comment]
Both of those names are pretty much what I was thinking of.  It takes me awhile to come up with names.  It is really difficult to name stuff well.

**Comment by henriquemoody** [comment]
Yeah... At least they reflect exactly what they are.

**Comment by AndyWendt** [comment]
For reference: 

AbstractNestedException extends ValidationException

AbstractNestedException is used by:

	* AbstractGroupedException
	* AttributeException
	* BetweenException
	* CallbackException
	* DomainException
	* EachException
	* NoneOfException
	* OneOfException
	* ZendException

AbstractGroupedException is used by:

	* AllOfException
	* AtLeastException
	* CallException
	* NotException


MostOfException extends AtLeastException
KeyException extends AttributeException

File: tests/Exceptions/AbstractNestedExceptionTest.php [hunk 7]
```diff
@@ -127,4 +134,3 @@ public function testFindMessagesShouldApplyTemplatesToFlattenedMessages()
         }
     }
 }
-
```
Comment (AndyWendt) [inline tests/Exceptions/AbstractNestedExceptionTest.php]: Two newlines were at end of file.  Github doesn't show the other one, but it is there if you clone the repo.

File: tests/Exceptions/ValidationExceptionTest.php [hunk 8]
```diff
@@ -98,4 +111,3 @@ public function providerForFormat()
         );
     }
 }
-
```
Comment (AndyWendt) [inline tests/Exceptions/ValidationExceptionTest.php]: Two newlines were at end of file. Github doesn't show the other one, but it is there if you clone the repo.

Comment (henriquemoody) [inline tests/Exceptions/ValidationExceptionTest.php]: Yeah, GitHub doesn't display the last line but there is an special char to indicate when there is no new line at end. That's why the common standard is to have one new line at the end of file, so, there is no need on having more than one, but just once.

File: README.md [hunk 9]
```diff
@@ -108,15 +108,29 @@ $usernameValidator->validate('alexandre gaigalas'); //false
...
+* `Repect\Validation\Exceptions\ExceptionInterface`: 
+    * All `Respect\Validation\Exceptions` implement this interface.  
+ 
 ### Informative Exceptions
 
 When something goes wrong, Validation can tell you exactly what's going on. For this,
 we use the `assert()` method instead of `validate()`:
 
 ```php
+import Respect\Validation\Exceptions\NestedValidationExceptionInterface
```
Comment (henriquemoody) [inline README.md]: `import` is not used on PHP, use `use` instead.

File: README.md [hunk 10]
```diff
@@ -134,9 +148,11 @@ The text tree is fine, but unusable on a HTML form or something more custom. You
 `findMessages()` for that:
 
 ```php
+import Respect\Validation\Exceptions\NestedValidationExceptionInterface
```
Comment (henriquemoody) [inline README.md]: [Same here](https://github.com/Respect/Validation/pull/272/files#r23883716).

File: README.md [hunk 11]
```diff
@@ -183,9 +199,11 @@ validation report. There is also a `check()` method that returns an Exception
 only with the first error found:
 
 ```php
+import Respect\Validation\Exceptions\ValidationExceptionInterface
```
Comment (henriquemoody) [inline README.md]: [Same here](https://github.com/Respect/Validation/pull/272/files#r23883716).

File: README.md [hunk 12]
```diff
@@ -183,9 +199,11 @@ validation report. There is also a `check()` method that returns an Exception
...
+
 try {
     $usernameValidator->check('really messed up screen#name');
-} catch(\InvalidArgumentException $e) {
+} catch(ValidationExceptionInterface $e) {
```
Comment (henriquemoody) [inline README.md]: Since you must change this file again, do you mind to rename `$e` to `$exception`?

File: library/Exceptions/ValidationExceptionInterface.php [hunk 13]
```diff
@@ -0,0 +1,6 @@
+<?php  namespace Respect\Validation\Exceptions;
+
+interface ValidationExceptionInterface
```
Comment (henriquemoody) [inline library/Exceptions/ValidationExceptionInterface.php]: Extends `ExceptionInterface`.

File: library/Exceptions/NestedValidationExceptionInterface.php [hunk 14]
```diff
@@ -0,0 +1,8 @@
+<?php
+namespace Respect\Validation\Exceptions;
+
+interface NestedValidationExceptionInterface extends ValidationExceptionInterface
```
Comment (henriquemoody) [inline library/Exceptions/NestedValidationExceptionInterface.php]: Also extends `ExceptionInterface`.

File: library/Exceptions/ValidationException.php [hunk 15]
```diff
@@ -2,10 +2,9 @@
 namespace Respect\Validation\Exceptions;
 
 use DateTime;
-use Exception;
 use InvalidArgumentException;
 
-class ValidationException extends InvalidArgumentException
+class ValidationException extends InvalidArgumentException implements ExceptionInterface, ValidationExceptionInterface
```
Comment (henriquemoody) [inline library/Exceptions/ValidationException.php]: Just `ValidationExceptionInterface`, since `ValidationExceptionInterface` must extends `ExceptionInterface`.

File: library/Exceptions/ValidationExceptionInterface.php [hunk 16]
```diff
@@ -0,0 +1,6 @@
+<?php  namespace Respect\Validation\Exceptions;
```
Comment (henriquemoody) [inline library/Exceptions/ValidationExceptionInterface.php]: You must add a new line after `<?php` and them declare the namespace.

File: library/Exceptions/ValidationException.php (hunk 15 above)
Comment (AndyWendt) [inline library/Exceptions/ValidationException.php]: I will have ValidationExceptionInterface extend ExceptionInterface

File: README.md (hunk 9 above)
Comment (AndyWendt) [inline README.md]: Too much python lately

File: README.md (hunk 12 above)
Comment (AndyWendt) [inline README.md]: Sure

File: README.md (hunk 9 above)
Comment (henriquemoody) [inline README.md]: hehehe, I was wondering if it was Python, C, Java or what :stuck_out_tongue_closed_eyes:

File: library/Exceptions/NestedValidationExceptionInterface.php (hunk 14 above)
Comment (AndyWendt) [inline library/Exceptions/NestedValidationExceptionInterface.php]: Since `ValidationExceptionInterface` will extend `ExceptionInterface` after I make some changes, do you still want me to also extend `ExceptionInterface` here?

Comment (henriquemoody) [inline library/Exceptions/NestedValidationExceptionInterface.php]: No, just `ValidationExceptionInterface` since extends `ExceptionInterface`.

File: library/Exceptions/ValidationException.php (hunk 15 above)
Comment (henriquemoody) [inline library/Exceptions/ValidationException.php]: :+1:

File: library/Exceptions/NestedValidationExceptionInterface.php (hunk 14 above)
Comment (AndyWendt) [inline library/Exceptions/NestedValidationExceptionInterface.php]: That's what I was thinking

File: library/Exceptions/ValidationExceptionInterface.php (hunk 16 above)
Comment (AndyWendt) [inline library/Exceptions/ValidationExceptionInterface.php]: I changed my file template :smile:

**Comment by henriquemoody** [comment]
Do you mind to squash these commits at once? 4 commits is too much for this change.

**Comment by AndyWendt** [comment]
You are right—it will look cleaner

**Comment by AndyWendt** [comment]
I squashed them into one

**Comment by henriquemoody** [comment]
@AndyWendt, looks like this pull request breaks HHVM build, can you investigate?

**Comment by AndyWendt** [comment]
Yes I can.  Any idea why this wasn't picked up by Travis originally?  I assume it was caught by Travis

**Comment by henriquemoody** [comment]
Because our Travis configuration allows failures on HHVM builds.

**Comment by AndyWendt** [comment]
Oh.  Got it.  I will go through and fix that.

**Comment by henriquemoody** [comment]
Thank you very much!

**Comment by AndyWendt** [comment]
It looks like phpunit has an issue with mocking exceptions while running in HHVM: https://github.com/sebastianbergmann/phpunit-mock-objects/issues/207

I am submitting a PR to master that will fix the tests.
